# Site settings
title: Antonino Reale
email: roberto@reale.me
description: SorrentoEventi.eu
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://antonino.reale.me" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://www.facebook.com/Sorrentoeventi
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
